# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xzOQXTjmwh_LYJHYqhFDavyP4hJgQEIT
"""

# ==========================================
# PRO STOCK AI APP (NSE + LSTM + REAL-TIME)
# ==========================================

# Install via requirements.txt (DO NOT use !pip here)

import streamlit as st
import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import LSTM, Dense, Dropout
import os

st.set_page_config(page_title="AI Stock Predictor", layout="wide")

st.title("📊 AI Stock Predictor (NSE + Real-Time + LSTM)")

# =========================
# NSE STOCK INPUT
# =========================
ticker = st.text_input("Enter NSE Stock (e.g., RELIANCE, TCS, INFY)", "RELIANCE")
ticker_symbol = ticker.upper() + ".NS"

# =========================
# LOAD DATA
# =========================
@st.cache_data
def load_data(symbol):
    data = yf.download(symbol, start="2015-01-01")
    return data

if st.button("Analyze Stock"):

    data = load_data(ticker_symbol)

    if data.empty:
        st.error("Invalid stock or no data found")
    else:
        st.subheader("📈 Live Price Chart")
        st.line_chart(data['Close'])

        # =========================
        # REAL-TIME PRICE
        # =========================
        current_price = data['Close'].iloc[-1]
        st.metric(label="Current Price", value=f"₹ {current_price:.2f}")

        # =========================
        # PREPROCESSING
        # =========================
        close_prices = data['Close'].values.reshape(-1, 1)
        scaler = MinMaxScaler(feature_range=(0, 1))
        scaled_data = scaler.fit_transform(close_prices)

        sequence_length = 60
        X, y = [], []

        for i in range(sequence_length, len(scaled_data)):
            X.append(scaled_data[i-sequence_length:i, 0])
            y.append(scaled_data[i, 0])

        X, y = np.array(X), np.array(y)
        X = np.reshape(X, (X.shape[0], X.shape[1], 1))

        split = int(0.8 * len(X))
        X_train, X_test = X[:split], X[split:]
        y_train, y_test = y[:split], y[split:]

        # =========================
        # MODEL LOAD / TRAIN
        # =========================
        model_path = f"{ticker_symbol}_model.h5"

        if os.path.exists(model_path):
            model = load_model(model_path)
            st.success("Loaded saved model ✅")
        else:
            model = Sequential()
            model.add(LSTM(50, return_sequences=True, input_shape=(X_train.shape[1], 1)))
            model.add(Dropout(0.2))
            model.add(LSTM(50))
            model.add(Dropout(0.2))
            model.add(Dense(1))

            model.compile(optimizer='adam', loss='mean_squared_error')

            with st.spinner("Training AI model..."):
                model.fit(X_train, y_train, epochs=5, batch_size=32, verbose=0)
                model.save(model_path)

            st.success("Model trained & saved 🚀")

        # =========================
        # PREDICTIONS
        # =========================
        predictions = model.predict(X_test)
        predictions = scaler.inverse_transform(predictions)
        actual = scaler.inverse_transform(y_test.reshape(-1, 1))

        st.subheader("📊 Prediction vs Actual")
        fig = plt.figure()
        plt.plot(actual, label='Actual')
        plt.plot(predictions, label='Predicted')
        plt.legend()
        st.pyplot(fig)

        # =========================
        # NEXT DAY PREDICTION
        # =========================
        last_60 = scaled_data[-60:]
        last_60 = np.reshape(last_60, (1, 60, 1))
        next_price = model.predict(last_60)
        next_price = scaler.inverse_transform(next_price)

        st.subheader("🔮 Next Day Prediction")
        st.success(f"₹ {next_price[0][0]:.2f}")

        # =========================
        # SIMPLE SIGNAL
        # =========================
        if next_price[0][0] > current_price:
            st.success("📈 BUY Signal")
        else:
            st.error("📉 SELL Signal")

# ==========================================
# DEPLOYMENT READY
# ==========================================
# requirements.txt:
# streamlit
# yfinance
# numpy
# pandas
# scikit-learn
# tensorflow-cpu
# matplotlib
# ==========================================